export const NAV_GROUPS = [
  { id: 'batches',     label: 'Batches',       icon: 'fa-object-group'    },
  { id: 'academics',   label: 'Academics',     icon: 'fa-graduation-cap'  },
  { id: 'people',      label: 'People',        icon: 'fa-users'           },
  { id: 'commerce',    label: 'Commerce',      icon: 'fa-shopping-cart'   },
  { id: 'marketing',   label: 'Marketing',     icon: 'fa-bullhorn'        },
  { id: 'support',     label: 'Support',       icon: 'fa-life-ring'       },
  { id: 'tools',       label: 'Tools',         icon: 'fa-wrench'          },
];

const screens = [
  // ── Public ───────────────────────────────────────────────────────────
  {
    path: '/login',
    title: 'Pilot Login',
    legacyHtml: 'index.html',
    controller: 'controllers/login.js',
    protected: false,
    group: null,
    icon: 'fa-sign-in',
    summary: 'Admin authentication and token bootstrap.',
  },
  {
    path: '/verify-token',
    title: 'Token Verification',
    legacyHtml: 'verify-token.html',
    controller: 'inline',
    protected: false,
    group: null,
    icon: 'fa-key',
    summary: 'Developer utility for token validation.',
  },

  // ── Batches ───────────────────────────────────────────────────────────
  {
    path: '/batch',
    title: 'Batch Management',
    legacyHtml: 'batch.html',
    controller: 'controllers/batch.js',
    protected: true,
    group: 'batches',
    icon: 'fa-object-group',
    shortCode: 'BM',
    summary: 'Batch CRUD, course enrollments, and student assignment.',
  },
  {
    path: '/live-class-scheduler',
    title: 'Live Class Scheduler',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'batches',
    icon: 'fa-video-camera',
    shortCode: 'LC',
    summary: 'Schedule, host, and moderate live interactive broadcast sessions.',
  },

  // ── Academics ─────────────────────────────────────────────────────────
  {
    path: '/courses-list',
    title: 'Courses',
    legacyHtml: 'courses-list.html',
    controller: 'controllers/courses-list.js',
    protected: true,
    group: 'academics',
    icon: 'fa-list-alt',
    shortCode: 'CR',
    summary: 'Published course listing, filters, and deep links.',
  },
  {
    path: '/test-series-list',
    title: 'Test Series',
    legacyHtml: 'test-series-list.html',
    controller: 'controllers/test-series-list.js',
    protected: true,
    group: 'academics',
    icon: 'fa-tasks',
    shortCode: 'TS',
    summary: 'Test-series definition and exam assignments.',
  },
  {
    path: '/quiz-listing',
    title: 'Quizzes',
    legacyHtml: 'quiz-listing.html',
    controller: 'controllers/quiz-listing.js',
    protected: true,
    group: 'academics',
    icon: 'fa-list-ul',
    shortCode: 'QZ',
    summary: 'Quiz drafts, published quizzes, and report entry points.',
  },
  {
    path: '/question-bank',
    title: 'Question Bank',
    legacyHtml: 'question-bank.html',
    controller: 'controllers/question-bank.js',
    protected: true,
    group: 'academics',
    icon: 'fa-database',
    shortCode: 'QB',
    summary: 'Question review, verification, solution editing, and filters.',
  },
  {
    path: '/practice-questions',
    title: 'Practice Questions',
    legacyHtml: 'practice-questions.html',
    controller: 'controllers/practice-questions.js',
    protected: true,
    group: 'academics',
    icon: 'fa-file-text-o',
    shortCode: 'PQ',
    summary: 'PDF ingestion, OCR-assisted extraction, and quiz handoff.',
  },
  {
    path: '/video-content',
    title: 'Video Library',
    legacyHtml: 'video-content.html',
    controller: 'controllers/video-content.js',
    protected: true,
    group: 'academics',
    icon: 'fa-video-camera',
    shortCode: 'VL',
    summary: 'Bunny.net video upload, filtering, and collection management.',
  },
  {
    path: '/bunny-admin',
    title: 'Video Hosting',
    legacyHtml: 'bunny-admin.html',
    controller: 'controllers/bunny-admin.js',
    protected: true,
    group: 'academics',
    icon: 'fa-film',
    shortCode: 'VH',
    summary: 'Folder-oriented Bunny.net admin surface.',
  },

  // ── People ────────────────────────────────────────────────────────────
  {
    path: '/candidate-profile',
    title: 'Students',
    legacyHtml: 'candidate-profile.html',
    controller: 'controllers/candidate-profile.js',
    protected: true,
    group: 'people',
    icon: 'fa-users',
    shortCode: 'ST',
    summary: 'Student listing, enrollment actions, and search.',
  },
  {
    path: '/mentor-profiles',
    title: 'Mentors',
    legacyHtml: 'mentor-profiles.html',
    controller: 'controllers/mentor-profiles.js',
    protected: true,
    group: 'people',
    icon: 'fa-user-secret',
    shortCode: 'MN',
    summary: 'Mentor CRUD plus assigned-student workflows.',
  },
  {
    path: '/instructor-portfolio',
    title: 'Instructors',
    legacyHtml: 'instructor-portfolio.html',
    controller: 'controllers/instructor-portfolio.js',
    protected: true,
    group: 'people',
    icon: 'fa-briefcase',
    shortCode: 'IN',
    summary: 'Instructor CRUD and profile asset management.',
  },

  // ── Commerce ──────────────────────────────────────────────────────────
  {
    path: '/orders',
    title: 'Orders',
    legacyHtml: 'orders.html',
    controller: 'controllers/orders.js',
    protected: true,
    group: 'commerce',
    icon: 'fa-shopping-cart',
    shortCode: 'OR',
    summary: 'Order tracking, invoice actions, and student drill-down.',
  },
  {
    path: '/catalog',
    title: 'Catalog',
    legacyHtml: 'catalog.html',
    controller: 'controllers/catalog.js',
    protected: true,
    group: 'commerce',
    icon: 'fa-th-large',
    shortCode: 'CT',
    summary: 'Catalog entries, publishing, and asset upload workflow.',
  },

  // ── Marketing ─────────────────────────────────────────────────────────
  {
    path: '/leads-management',
    title: 'Leads',
    legacyHtml: 'leads-management.html',
    controller: 'controllers/leads.js',
    protected: true,
    group: 'marketing',
    icon: 'fa-bullhorn',
    shortCode: 'LD',
    summary: 'Lead tracking, follow-up calendar, and outreach actions.',
  },
  {
    path: '/messenger',
    title: 'Broadcast Messages',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'marketing',
    icon: 'fa-paper-plane',
    shortCode: 'BMG',
    summary: 'Send bulk messages to students via multi-channel broadcasts.',
  },
  {
    path: '/web-content-manager',
    title: 'Web Content Manager',
    legacyHtml: 'web-content-manager.html',
    controller: 'controllers/web-content-manager.js',
    protected: true,
    group: 'marketing',
    icon: 'fa-globe',
    shortCode: 'WC',
    summary: 'Voucher and auto-enrollment management.',
  },

  // ── Support ───────────────────────────────────────────────────────────
  {
    path: '/support',
    title: 'Support Tickets',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'support',
    icon: 'fa-life-ring',
    shortCode: 'SP',
    summary: 'Consolidated view for student support tickets and potential leads chats.',
  },

  // ── Tools ─────────────────────────────────────────────────────────────
  {
    path: '/feedback-summary',
    title: 'Feedbacks',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'tools',
    icon: 'fa-star-half-o',
    shortCode: 'FD',
    summary: 'Consolidated feedback aggregation and viewing portal.',
  },
  {
    path: '/survey-dashboard',
    title: 'Surveys',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'tools',
    icon: 'fa-bar-chart',
    shortCode: 'SR',
    summary: 'Create custom surveys and view responses across targeted student batches.',
  },
  {
    path: '/instructor-payouts',
    title: 'Instructor Payouts',
    legacyHtml: 'instructor-payouts.html',
    controller: 'controllers/instructor-time-tracker.js',
    protected: true,
    group: 'tools',
    icon: 'fa-money',
    shortCode: 'IP',
    summary: 'Time tracking and payout calculations.',
  },

  // ── Hidden (no sidebar entry) ─────────────────────────────────────────
  {
    path: '/candidate-detail',
    title: 'Student Details',
    legacyHtml: 'candidate-detail.html',
    controller: 'controllers/candidate-detail.js',
    protected: true,
    group: null,
    icon: 'fa-user-circle-o',
    summary: 'Detailed candidate profile, mentor, courses, and exam history.',
  },
  {
    path: '/course-view',
    title: 'Course View',
    legacyHtml: 'course-view.html',
    controller: 'controllers/course-view.js',
    protected: true,
    group: null,
    icon: 'fa-eye',
    summary: 'Course detail viewer with chapter and part navigation.',
  },
  {
    path: '/course-management',
    title: 'Course Management',
    legacyHtml: 'course-management.html',
    controller: 'controllers/course-management.js',
    protected: true,
    group: null,
    icon: 'fa-pencil',
    summary: 'Course authoring, syllabus management, and chapter linking.',
  },
  {
    path: '/live-class-activity-planner',
    title: 'Activity Planner',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: null,
    icon: 'fa-gamepad',
    summary: 'Pre-configure polls and quizzes for upcoming live classes.',
  },
  {
    path: '/quiz-creation',
    title: 'Quiz Creation',
    legacyHtml: 'quiz-creation.html',
    controller: 'controllers/quiz-creation.js',
    protected: true,
    group: null,
    icon: 'fa-plus-square-o',
    summary: 'Quiz assembly from practice-question bundles.',
  },
  {
    path: '/quiz-attempt-report',
    title: 'Quiz Report',
    legacyHtml: 'quiz-attempt-report.html',
    controller: 'controllers/quiz-attempt-report.js',
    protected: true,
    group: null,
    icon: 'fa-bar-chart',
    summary: 'Quiz attempt analytics and export tools.',
  },
  {
    path: '/exam-listing',
    title: 'Exams',
    legacyHtml: 'exam-listing.html',
    controller: 'controllers/exam-listing.js',
    protected: true,
    group: null,
    icon: 'fa-graduation-cap',
    summary: 'Exam list, duplication, deletion, and report entry points.',
  },
  {
    path: '/exam-creation-wizard',
    title: 'Exam Creation Wizard',
    legacyHtml: 'exam-creation-wizard.html',
    controller: 'controllers/exam-creation-wizard.js',
    protected: true,
    group: null,
    icon: 'fa-magic',
    summary: 'Exam editor and section/question configuration.',
  },
  {
    path: '/exam-attempt-report',
    title: 'Exam Report',
    legacyHtml: 'exam-attempt-report.html',
    controller: 'controllers/exam-attempt-report.js',
    protected: true,
    group: null,
    icon: 'fa-line-chart',
    summary: 'Exam attempt analytics and export tools.',
  },
];

export const publicScreens = screens.filter((screen) => !screen.protected);
export const protectedScreens = screens.filter((screen) => screen.protected);
export const allScreens = screens;
export const defaultProtectedRoute = '/candidate-profile';
