const screens = [
  {
    path: '/index.html',
    title: 'Pilot Login',
    legacyHtml: 'index.html',
    controller: 'controllers/login.js',
    protected: false,
    summary: 'Admin authentication and token bootstrap.',
  },
  {
    path: '/verify-token.html',
    title: 'Token Verification',
    legacyHtml: 'verify-token.html',
    controller: 'inline',
    protected: false,
    summary: 'Developer utility for token validation.',
  },
  {
    path: '/candidate-profile.html',
    title: 'Student Management',
    legacyHtml: 'candidate-profile.html',
    controller: 'controllers/candidate-profile.js',
    protected: true,
    summary: 'Student listing, enrollment actions, and search.',
  },
  {
    path: '/candidate-detail.html',
    title: 'Student Details',
    legacyHtml: 'candidate-detail.html',
    controller: 'controllers/candidate-detail.js',
    protected: true,
    summary: 'Detailed candidate profile, mentor, courses, and exam history.',
  },
  {
    path: '/orders.html',
    title: 'Orders Management',
    legacyHtml: 'orders.html',
    controller: 'controllers/orders.js',
    protected: true,
    summary: 'Order tracking, invoice actions, and student drill-down.',
  },
  {
    path: '/courses-list.html',
    title: 'Courses List',
    legacyHtml: 'courses-list.html',
    controller: 'controllers/courses-list.js',
    protected: true,
    summary: 'Published course listing, filters, and deep links.',
  },
  {
    path: '/course-view.html',
    title: 'Course View',
    legacyHtml: 'course-view.html',
    controller: 'controllers/course-view.js',
    protected: true,
    summary: 'Course detail viewer with chapter and part navigation.',
  },
  {
    path: '/course-management.html',
    title: 'Course Management',
    legacyHtml: 'course-management.html',
    controller: 'controllers/course-management.js',
    protected: true,
    summary: 'Course authoring, syllabus management, and chapter linking.',
  },
  {
    path: '/catalog.html',
    title: 'Catalog Management',
    legacyHtml: 'catalog.html',
    controller: 'controllers/catalog.js',
    protected: true,
    summary: 'Catalog entries, publishing, and asset upload workflow.',
  },
  {
    path: '/video-content.html',
    title: 'Video Content',
    legacyHtml: 'video-content.html',
    controller: 'controllers/video-content.js',
    protected: true,
    summary: 'Bunny.net video upload, filtering, and collection management.',
  },
  {
    path: '/bunny-admin.html',
    title: 'Video Management',
    legacyHtml: 'bunny-admin.html',
    controller: 'controllers/bunny-admin.js',
    protected: true,
    summary: 'Folder-oriented Bunny.net admin surface.',
  },
  {
    path: '/quiz-listing.html',
    title: 'Quiz Listing',
    legacyHtml: 'quiz-listing.html',
    controller: 'controllers/quiz-listing.js',
    protected: true,
    summary: 'Quiz drafts, published quizzes, and report entry points.',
  },
  {
    path: '/quiz-creation.html',
    title: 'Quiz Creation',
    legacyHtml: 'quiz-creation.html',
    controller: 'controllers/quiz-creation.js',
    protected: true,
    summary: 'Quiz assembly from practice-question bundles.',
  },
  {
    path: '/quiz-attempt-report.html',
    title: 'Quiz Report',
    legacyHtml: 'quiz-attempt-report.html',
    controller: 'controllers/quiz-attempt-report.js',
    protected: true,
    summary: 'Quiz attempt analytics and export tools.',
  },
  {
    path: '/question-bank.html',
    title: 'Question Bank',
    legacyHtml: 'question-bank.html',
    controller: 'controllers/question-bank.js',
    protected: true,
    summary: 'Question review, verification, solution editing, and filters.',
  },
  {
    path: '/practice-questions.html',
    title: 'Practice Questions',
    legacyHtml: 'practice-questions.html',
    controller: 'controllers/practice-questions.js',
    protected: true,
    summary: 'PDF ingestion, OCR-assisted extraction, and quiz handoff.',
  },
  {
    path: '/exam-listing.html',
    title: 'Exam Listing',
    legacyHtml: 'exam-listing.html',
    controller: 'controllers/exam-listing.js',
    protected: true,
    summary: 'Exam list, duplication, deletion, and report entry points.',
  },
  {
    path: '/exam-creation-wizard.html',
    title: 'Exam Creation Wizard',
    legacyHtml: 'exam-creation-wizard.html',
    controller: 'controllers/exam-creation-wizard.js',
    protected: true,
    summary: 'Exam editor and section/question configuration.',
  },
  {
    path: '/exam-attempt-report.html',
    title: 'Exam Report',
    legacyHtml: 'exam-attempt-report.html',
    controller: 'controllers/exam-attempt-report.js',
    protected: true,
    summary: 'Exam attempt analytics and export tools.',
  },
  {
    path: '/test-series-list.html',
    title: 'Test Series List',
    legacyHtml: 'test-series-list.html',
    controller: 'controllers/test-series-list.js',
    protected: true,
    summary: 'Test-series definition and exam assignments.',
  },
  {
    path: '/mentor-profiles.html',
    title: 'Mentor Profiles',
    legacyHtml: 'mentor-profiles.html',
    controller: 'controllers/mentor-profiles.js',
    protected: true,
    summary: 'Mentor CRUD plus assigned-student workflows.',
  },
  {
    path: '/instructor-portfolio.html',
    title: 'Instructor Portfolio',
    legacyHtml: 'instructor-portfolio.html',
    controller: 'controllers/instructor-portfolio.js',
    protected: true,
    summary: 'Instructor CRUD and profile asset management.',
  },
  {
    path: '/instructor-payouts.html',
    title: 'Instructor Payouts',
    legacyHtml: 'instructor-payouts.html',
    controller: 'controllers/instructor-time-tracker.js',
    protected: true,
    summary: 'Time tracking and payout calculations.',
  },
  {
    path: '/leads-management.html',
    title: 'Leads Management',
    legacyHtml: 'leads-management.html',
    controller: 'controllers/leads.js',
    protected: true,
    summary: 'Lead tracking, follow-up calendar, and outreach actions.',
  },
  {
    path: '/batch.html',
    title: 'Batch Management',
    legacyHtml: 'batch.html',
    controller: 'controllers/batch.js',
    protected: true,
    summary: 'Batch CRUD, course enrollments, and student assignment.',
  },
  {
    path: '/web-content-manager.html',
    title: 'Web Content Manager',
    legacyHtml: 'web-content-manager.html',
    controller: 'controllers/web-content-manager.js',
    protected: true,
    summary: 'Voucher and auto-enrollment management.',
  },
];

export const publicScreens = screens.filter((screen) => !screen.protected);
export const protectedScreens = screens.filter((screen) => screen.protected);
export const allScreens = screens;
export const defaultProtectedRoute = '/candidate-profile.html';
