export const NAV_GROUPS = [
  { id: 'students',    label: 'Students',     icon: 'fa-users'           },
  { id: 'orders',      label: 'Orders',        icon: 'fa-shopping-cart'   },
  { id: 'courses',     label: 'Courses',       icon: 'fa-book'            },
  { id: 'assessments', label: 'Assessments',   icon: 'fa-pencil-square-o' },
  { id: 'exams',       label: 'Exams',         icon: 'fa-graduation-cap'  },
  { id: 'people',      label: 'People',        icon: 'fa-id-badge'        },
  { id: 'ops',         label: 'Operations',    icon: 'fa-cogs'            },
];

const screens = [
  {
    path: '/login',
    title: 'Pilot Login',
    legacyHtml: 'index.html',
    controller: 'controllers/login.js',
    protected: false,
    group: null,
    icon: 'fa-sign-in',
    summary: 'Admin authentication and token bootstrap.',
  },
  {
    path: '/verify-token',
    title: 'Token Verification',
    legacyHtml: 'verify-token.html',
    controller: 'inline',
    protected: false,
    group: null,
    icon: 'fa-key',
    summary: 'Developer utility for token validation.',
  },
  {
    path: '/candidate-profile',
    title: 'Student Management',
    legacyHtml: 'candidate-profile.html',
    controller: 'controllers/candidate-profile.js',
    protected: true,
    group: 'students',
    icon: 'fa-users',
    summary: 'Student listing, enrollment actions, and search.',
  },
  {
    path: '/candidate-detail',
    title: 'Student Details',
    legacyHtml: 'candidate-detail.html',
    controller: 'controllers/candidate-detail.js',
    protected: true,
    group: 'students',
    icon: 'fa-user-circle-o',
    summary: 'Detailed candidate profile, mentor, courses, and exam history.',
  },
  {
    path: '/orders',
    title: 'Orders Management',
    legacyHtml: 'orders.html',
    controller: 'controllers/orders.js',
    protected: true,
    group: 'orders',
    icon: 'fa-shopping-cart',
    summary: 'Order tracking, invoice actions, and student drill-down.',
  },
  {
    path: '/courses-list',
    title: 'Courses List',
    legacyHtml: 'courses-list.html',
    controller: 'controllers/courses-list.js',
    protected: true,
    group: 'courses',
    icon: 'fa-list-alt',
    summary: 'Published course listing, filters, and deep links.',
  },
  {
    path: '/course-view',
    title: 'Course View',
    legacyHtml: 'course-view.html',
    controller: 'controllers/course-view.js',
    protected: true,
    group: 'courses',
    icon: 'fa-eye',
    summary: 'Course detail viewer with chapter and part navigation.',
  },
  {
    path: '/course-management',
    title: 'Course Management',
    legacyHtml: 'course-management.html',
    controller: 'controllers/course-management.js',
    protected: true,
    group: 'courses',
    icon: 'fa-pencil',
    summary: 'Course authoring, syllabus management, and chapter linking.',
  },
  {
    path: '/catalog',
    title: 'Catalog Management',
    legacyHtml: 'catalog.html',
    controller: 'controllers/catalog.js',
    protected: true,
    group: 'courses',
    icon: 'fa-th-large',
    summary: 'Catalog entries, publishing, and asset upload workflow.',
  },
  {
    path: '/video-content',
    title: 'Video Content',
    legacyHtml: 'video-content.html',
    controller: 'controllers/video-content.js',
    protected: true,
    group: 'courses',
    icon: 'fa-video-camera',
    summary: 'Bunny.net video upload, filtering, and collection management.',
  },
  {
    path: '/bunny-admin',
    title: 'Video Management',
    legacyHtml: 'bunny-admin.html',
    controller: 'controllers/bunny-admin.js',
    protected: true,
    group: 'courses',
    icon: 'fa-film',
    summary: 'Folder-oriented Bunny.net admin surface.',
  },
  {
    path: '/quiz-listing',
    title: 'Quiz Listing',
    legacyHtml: 'quiz-listing.html',
    controller: 'controllers/quiz-listing.js',
    protected: true,
    group: 'assessments',
    icon: 'fa-list-ul',
    summary: 'Quiz drafts, published quizzes, and report entry points.',
  },
  {
    path: '/quiz-creation',
    title: 'Quiz Creation',
    legacyHtml: 'quiz-creation.html',
    controller: 'controllers/quiz-creation.js',
    protected: true,
    group: 'assessments',
    icon: 'fa-plus-square-o',
    summary: 'Quiz assembly from practice-question bundles.',
  },
  {
    path: '/quiz-attempt-report',
    title: 'Quiz Report',
    legacyHtml: 'quiz-attempt-report.html',
    controller: 'controllers/quiz-attempt-report.js',
    protected: true,
    group: 'assessments',
    icon: 'fa-bar-chart',
    summary: 'Quiz attempt analytics and export tools.',
  },
  {
    path: '/question-bank',
    title: 'Question Bank',
    legacyHtml: 'question-bank.html',
    controller: 'controllers/question-bank.js',
    protected: true,
    group: 'assessments',
    icon: 'fa-database',
    summary: 'Question review, verification, solution editing, and filters.',
  },
  {
    path: '/practice-questions',
    title: 'Practice Questions',
    legacyHtml: 'practice-questions.html',
    controller: 'controllers/practice-questions.js',
    protected: true,
    group: 'assessments',
    icon: 'fa-file-text-o',
    summary: 'PDF ingestion, OCR-assisted extraction, and quiz handoff.',
  },
  {
    path: '/exam-listing',
    title: 'Exam Listing',
    legacyHtml: 'exam-listing.html',
    controller: 'controllers/exam-listing.js',
    protected: true,
    group: 'exams',
    icon: 'fa-graduation-cap',
    summary: 'Exam list, duplication, deletion, and report entry points.',
  },
  {
    path: '/exam-creation-wizard',
    title: 'Exam Creation Wizard',
    legacyHtml: 'exam-creation-wizard.html',
    controller: 'controllers/exam-creation-wizard.js',
    protected: true,
    group: 'exams',
    icon: 'fa-magic',
    summary: 'Exam editor and section/question configuration.',
  },
  {
    path: '/exam-attempt-report',
    title: 'Exam Report',
    legacyHtml: 'exam-attempt-report.html',
    controller: 'controllers/exam-attempt-report.js',
    protected: true,
    group: 'exams',
    icon: 'fa-line-chart',
    summary: 'Exam attempt analytics and export tools.',
  },
  {
    path: '/test-series-list',
    title: 'Test Series List',
    legacyHtml: 'test-series-list.html',
    controller: 'controllers/test-series-list.js',
    protected: true,
    group: 'exams',
    icon: 'fa-tasks',
    summary: 'Test-series definition and exam assignments.',
  },
  {
    path: '/mentor-profiles',
    title: 'Mentor Profiles',
    legacyHtml: 'mentor-profiles.html',
    controller: 'controllers/mentor-profiles.js',
    protected: true,
    group: 'people',
    icon: 'fa-user-secret',
    summary: 'Mentor CRUD plus assigned-student workflows.',
  },
  {
    path: '/instructor-portfolio',
    title: 'Instructor Portfolio',
    legacyHtml: 'instructor-portfolio.html',
    controller: 'controllers/instructor-portfolio.js',
    protected: true,
    group: 'people',
    icon: 'fa-briefcase',
    summary: 'Instructor CRUD and profile asset management.',
  },
  {
    path: '/instructor-payouts',
    title: 'Instructor Payouts',
    legacyHtml: 'instructor-payouts.html',
    controller: 'controllers/instructor-time-tracker.js',
    protected: true,
    group: 'people',
    icon: 'fa-money',
    summary: 'Time tracking and payout calculations.',
  },
  {
    path: '/leads-management',
    title: 'Leads Management',
    legacyHtml: 'leads-management.html',
    controller: 'controllers/leads.js',
    protected: true,
    group: 'ops',
    icon: 'fa-bullhorn',
    summary: 'Lead tracking, follow-up calendar, and outreach actions.',
  },
  {
    path: '/batch',
    title: 'Batch Management',
    legacyHtml: 'batch.html',
    controller: 'controllers/batch.js',
    protected: true,
    group: 'ops',
    icon: 'fa-object-group',
    summary: 'Batch CRUD, course enrollments, and student assignment.',
  },
  {
    path: '/web-content-manager',
    title: 'Web Content Manager',
    legacyHtml: 'web-content-manager.html',
    controller: 'controllers/web-content-manager.js',
    protected: true,
    group: 'ops',
    icon: 'fa-globe',
    summary: 'Voucher and auto-enrollment management.',
  },
];

export const publicScreens = screens.filter((screen) => !screen.protected);
export const protectedScreens = screens.filter((screen) => screen.protected);
export const allScreens = screens;
export const defaultProtectedRoute = '/candidate-profile';
