import React, { useMemo, useState } from 'react';
import ToastRegion from '../components/ToastRegion';
import { batchesDemo } from '../data/adminRemainingDemo';

export default function BatchManagementPage() {
  const [batches, setBatches] = useState(batchesDemo);
  const [searchQuery, setSearchQuery] = useState('');
  const [editingBatch, setEditingBatch] = useState(null);
  const [selectedBatch, setSelectedBatch] = useState(null);
  const [toasts, setToasts] = useState([]);
  function showToast(type, title, message) { const id = Date.now() + Math.random(); setToasts((current) => [...current, { id, type, title, message }]); window.setTimeout(() => setToasts((current) => current.filter((toast) => toast.id !== id)), 4000); }
  const filtered = useMemo(() => batches.filter((batch) => !searchQuery.trim() || [batch.batchName, batch.description].some((value) => String(value).toLowerCase().includes(searchQuery.trim().toLowerCase()))), [batches, searchQuery]);
  return (
    <section className="screen-card">
      <ToastRegion toasts={toasts} onDismiss={(id) => setToasts((current) => current.filter((toast) => toast.id !== id))} />
      <div className="hero-row"><div><p className="eyebrow">Batches</p><h3>Batch Management</h3><p className="muted-copy">Batch CRUD, course enrollment, student assignment, and freeze toggles.</p></div><button type="button" className="primary-button" onClick={() => setEditingBatch({ batchName: '', numberOfStudents: 0, description: '', startDate: '', endDate: '', active: 1, isFrozen: false, enrolledCourses: [], students: [] })}>Create Batch</button></div>
      <div className="toolbar-row"><div className="search-shell"><input className="search-input" placeholder="Search batches..." value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} /></div></div>
      <div className="student-table-shell"><table className="student-table"><thead><tr><th>Batch</th><th>Students</th><th>Courses</th><th>Dates</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((batch) => <tr key={batch.id}><td><strong>{batch.batchName}</strong><div className="student-subtle">{batch.description}</div></td><td><button type="button" className="link-chip" onClick={() => setSelectedBatch(batch)}>{batch.students.length}/{batch.numberOfStudents}</button></td><td><div className="chip-row">{batch.enrolledCourses.length ? batch.enrolledCourses.map((course) => <span key={`${batch.id}-${course}`} className="status-pill">{course}</span>) : <span className="student-subtle">Not enrolled</span>}</div></td><td>{batch.startDate} to {batch.endDate}</td><td><div className="chip-row"><span className={`status-pill ${batch.active ? 'active' : 'inactive'}`}>{batch.active ? 'Active' : 'Inactive'}</span>{batch.isFrozen ? <span className="status-pill expired">Frozen</span> : null}</div></td><td><div className="action-row"><button type="button" className="table-button" onClick={() => setEditingBatch(batch)}>Edit</button><button type="button" className="table-button" onClick={() => { setBatches((current) => current.map((entry) => entry.id === batch.id ? { ...entry, isFrozen: !entry.isFrozen } : entry)); showToast('success', 'Batch Updated', `${batch.batchName} freeze status updated.`); }}>{batch.isFrozen ? 'Unfreeze' : 'Freeze'}</button></div></td></tr>)}</tbody></table></div>
      {selectedBatch ? <div className="modal-scrim" role="presentation" onClick={() => setSelectedBatch(null)}><div className="modal-card" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><p className="eyebrow">Batch Students</p><h4>{selectedBatch.batchName}</h4><div className="stack-grid">{selectedBatch.students.map((student) => <div key={`${selectedBatch.id}-${student}`} className="detail-panel">{student}</div>)}</div><div className="action-row"><button type="button" className="ghost-button" onClick={() => setSelectedBatch(null)}>Close</button></div></div></div> : null}
      {editingBatch ? <div className="modal-scrim" role="presentation" onClick={() => setEditingBatch(null)}><div className="modal-card" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><p className="eyebrow">Batch Form</p><h4>{editingBatch.id ? 'Edit Batch' : 'Create Batch'}</h4><div className="form-grid"><label><span>Batch Name</span><input className="search-input" value={editingBatch.batchName} onChange={(event) => setEditingBatch((current) => ({ ...current, batchName: event.target.value }))} /></label><label><span>Capacity</span><input className="search-input" type="number" value={editingBatch.numberOfStudents} onChange={(event) => setEditingBatch((current) => ({ ...current, numberOfStudents: Number(event.target.value) }))} /></label><label className="full-span"><span>Description</span><textarea className="search-input textarea-like" value={editingBatch.description} onChange={(event) => setEditingBatch((current) => ({ ...current, description: event.target.value }))} /></label></div><div className="action-row"><button type="button" className="ghost-button" onClick={() => setEditingBatch(null)}>Cancel</button><button type="button" className="primary-button" onClick={() => { setBatches((current) => editingBatch.id ? current.map((entry) => entry.id === editingBatch.id ? editingBatch : entry) : [{ ...editingBatch, id: `B-${Date.now()}` }, ...current]); setEditingBatch(null); showToast('success', 'Batch Saved', 'Batch saved successfully.'); }}>Save</button></div></div></div> : null}
    </section>
  );
}
