import React, { useState } from 'react';
import ToastRegion from '../components/ToastRegion';
import { autoEnrollCoursesDemo, vouchersDemo } from '../data/adminRemainingDemo';

export default function WebContentManagerPage() {
  const [autoEnroll, setAutoEnroll] = useState(autoEnrollCoursesDemo);
  const [vouchers, setVouchers] = useState(vouchersDemo);
  const [selectedVoucher, setSelectedVoucher] = useState(null);
  const [editingVoucher, setEditingVoucher] = useState(null);
  const [toasts, setToasts] = useState([]);
  function showToast(type, title, message) { const id = Date.now() + Math.random(); setToasts((current) => [...current, { id, type, title, message }]); window.setTimeout(() => setToasts((current) => current.filter((toast) => toast.id !== id)), 4000); }
  return (
    <section className="screen-card">
      <ToastRegion toasts={toasts} onDismiss={(id) => setToasts((current) => current.filter((toast) => toast.id !== id))} />
      <div className="hero-row"><div><p className="eyebrow">Web Content</p><h3>Web Content Manager</h3><p className="muted-copy">Auto-enrollment courses and voucher management.</p></div><div className="action-row"><button type="button" className="ghost-button" onClick={() => { setAutoEnroll((current) => [...current, { code: `CR${Date.now()}`, title: 'New Auto Enroll Course', validityDays: 30 }]); showToast('success', 'Course Added', 'Course added to auto-enrollment configuration.'); }}>Add Auto-Enroll Course</button><button type="button" className="primary-button" onClick={() => setEditingVoucher({ code: '', title: '', amountType: 'fixed', amount: 0, status: 'active', validUntil: '', limitedUsers: false, users: [] })}>Create Voucher</button></div></div>
      <div className="detail-grid">
        <div className="detail-panel"><h4>Auto-Enroll Courses</h4><div className="stack-grid">{autoEnroll.map((course) => <div key={course.code} className="detail-panel"><strong>{course.title}</strong><p className="muted-copy">{course.code} · {course.validityDays} days</p></div>)}</div></div>
        <div className="detail-panel"><h4>Vouchers</h4><div className="student-table-shell nested-shell"><table className="student-table"><thead><tr><th>Code</th><th>Title</th><th>Value</th><th>Status</th><th>Users</th><th>Actions</th></tr></thead><tbody>{vouchers.map((voucher) => <tr key={voucher.id}><td>{voucher.code}</td><td>{voucher.title}</td><td>{voucher.amountType === 'percentage' ? `${voucher.amount}%` : `Rs. ${voucher.amount}`}</td><td><span className={`status-pill ${voucher.status === 'active' ? 'active' : 'inactive'}`}>{voucher.status}</span></td><td><button type="button" className="link-chip" onClick={() => setSelectedVoucher(voucher)}>{voucher.users.length} users</button></td><td><div className="action-row"><button type="button" className="table-button" onClick={() => setEditingVoucher(voucher)}>Edit</button><button type="button" className="table-button danger" onClick={() => { setVouchers((current) => current.map((entry) => entry.id === voucher.id ? { ...entry, status: 'revoked' } : entry)); showToast('success', 'Voucher Revoked', `${voucher.code} revoked.`); }}>Revoke</button></div></td></tr>)}</tbody></table></div></div>
      </div>
      {selectedVoucher ? <div className="modal-scrim" role="presentation" onClick={() => setSelectedVoucher(null)}><div className="modal-card" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><p className="eyebrow">Voucher Users</p><h4>{selectedVoucher.code}</h4><div className="stack-grid">{selectedVoucher.users.length ? selectedVoucher.users.map((user, index) => <div key={`${selectedVoucher.id}-${index}`} className="detail-panel"><strong>{user.name}</strong><p className="muted-copy">{user.phone}</p></div>) : <p className="muted-copy">No user limit configured.</p>}</div><div className="action-row"><button type="button" className="ghost-button" onClick={() => setSelectedVoucher(null)}>Close</button></div></div></div> : null}
      {editingVoucher ? <div className="modal-scrim" role="presentation" onClick={() => setEditingVoucher(null)}><div className="modal-card" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><p className="eyebrow">Voucher Form</p><h4>{editingVoucher.id ? 'Edit Voucher' : 'Create Voucher'}</h4><div className="form-grid"><label><span>Code</span><input className="search-input" value={editingVoucher.code} onChange={(event) => setEditingVoucher((current) => ({ ...current, code: event.target.value }))} /></label><label><span>Title</span><input className="search-input" value={editingVoucher.title} onChange={(event) => setEditingVoucher((current) => ({ ...current, title: event.target.value }))} /></label><label><span>Amount Type</span><select className="filter-select" value={editingVoucher.amountType} onChange={(event) => setEditingVoucher((current) => ({ ...current, amountType: event.target.value }))}><option value="fixed">Fixed</option><option value="percentage">Percentage</option></select></label><label><span>Amount</span><input className="search-input" type="number" value={editingVoucher.amount} onChange={(event) => setEditingVoucher((current) => ({ ...current, amount: Number(event.target.value) }))} /></label></div><div className="action-row"><button type="button" className="ghost-button" onClick={() => setEditingVoucher(null)}>Cancel</button><button type="button" className="primary-button" onClick={() => { setVouchers((current) => editingVoucher.id ? current.map((entry) => entry.id === editingVoucher.id ? editingVoucher : entry) : [{ ...editingVoucher, id: `VOC-${Date.now()}` }, ...current]); setEditingVoucher(null); showToast('success', 'Voucher Saved', 'Voucher saved successfully.'); }}>Save</button></div></div></div> : null}
    </section>
  );
}
